[package]
name = "siquery"
version = "0.1.0"
authors = ["SÃ©bastien Duquette <sduquette@devolutions.net>"]

[dependencies]
cfg-if = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1.0.0"
lazy_static = "1.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
uname = "0.1.1"

[target.'cfg(target_os = "linux")'.dependencies.sysconf]
version = "0.3.1"
git = "https://github.com/wayk/sysconf.rs"


[target.'cfg(target_os = "macos")'.dependencies]
plist-rs = "0.1.0"
uname = "0.1.1"